#!/usr/bin/env bash
#install ufw frewall and setup few rules

sudo apt-get -y install ufw
sudo sed i "s/IPV6=.*/IPV6=yes/" /etc/default/ufw
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 22
sudo ufw allow 80
sudo ufw allow 443
sudo ufw enable
